SQLGETALL_SP = "SELECT * FROM vwDanhSachSanPhamVaAnh"
SQLGETALL_NCC = "SELECT * FROM tbNhaCungCap"
SQLGETALL_NV = "SELECT * FROM tbNhanVien"
SQLGETALL_KH = "SELECT * FROM tbKhachHang"
SQLGETALL_DM = "SELECT * FROM tbDanhMuc"
SQLGETALL_User = "SELECT * FROM tbUser"
SQL_UserLogin = "SELECT * FROM Users WHERE (Email = %s OR SĐT = %s) AND PassWord = %s"
SQLGETALL_DONXULY_CT = "select *  from View_DonXuLy"
SQLGETALL_DOXL = "select * from tbDonHang where TrangThai = N'Chờ xử lý'"